server:
  port: 8052

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8051
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderServiceFallback
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productServiceFallback
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentServiceFallback

    compatibility-verifier:
      enabled: false


  sleuth:
    sampler:
      probability: 1.0

zipkin:
  base-url: http://localhost:9411

management:
  tracing:
    enabled: true
  metrics:
    export:
      simple:
        enabled: true
      prometheus:
        enabled: true

