server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_db
    username: root
    password: getoffer2024...
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8051

#  cloud:
#    compatibility-verifier:
#      enabled: false
#
#
#  sleuth:
#    sampler:
#      probability: 1.0
#
#zipkin:
#  base-url: http://localhost:9411
#
#management:
#  tracing:
#    enabled: true
#  metrics:
#    export:
#      simple:
#        enabled: true
#      prometheus:
#        enabled: true




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}



