server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_db
    username: root
    password: getoffer2024...
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

