server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order_db
    username: root
    password: getoffer2024...
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8051

#  cloud:
#    compatibility-verifier:
#      enabled: false
#
#
#  sleuth:
#    sampler:
#      probability: 1.0
#
#zipkin:
#  base-url: http://localhost:9411
#
#management:
#  tracing:
#    enabled: true
#  metrics:
#    export:
#      simple:
#        enabled: true
#      prometheus:
#        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      feignCall:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}

